Dai so tuyen tinh
- Ma tran: la m hang va n cot
- Vecto: la mang hoac danh sach cac so

In [11]:
import numpy as np
#Cong ma tran
A = np.array([[3,4],[5,6]])
B = np.array([[7,8],[9,10]])

C = A + B
print("A + B = \n", C)

D = np.dot(A, B)
print("A * B = \n", D)

#Nhan ma tran vs vo huong
print("Nhan ma tran voi vo huong")
C = np.array([[2,3],[4,5]])
F = 3 * C
print("3 * C = \n", F)  

#Nhan ma tran voi vecto 
print("Nhan ma tran voi vecto")
D = np.array([[1,2],[3,4]])
V = np.array([1,3])
G = np.dot(D, V)
print("D * v = \n", G)

#tich vo huong 2 vecto
print("Tich vo huong 2 vecto")
u = np.array([1,2,3])
v = np.array([4,5,6])
H = np.dot(u, v)
print("u * v = ", H)

#gia he phuong trinh tuyen tinh
print("Giai he phuong trinh tuyen tinh")
A = np.array([[2,3],[4,5]])
B = np.array([5,11])
X = np.linalg.solve(A, B)
print("Nghiem cua he phuong trinh la: ", X)

#cong vecto
print("Cong vecto")
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
v3 = v1 + v2
print("v1 + v2 = ", v3)

#chuyen vi
print("Chuyen vi")
M = np.array([[1,2,3],[4,5,6]])
M_T = np.transpose(M)
print("Chuyen vi cua M la: \n", M_T)



A + B = 
 [[10 12]
 [14 16]]
A * B = 
 [[ 57  64]
 [ 89 100]]
Nhan ma tran voi vo huong
3 * C = 
 [[ 6  9]
 [12 15]]
Nhan ma tran voi vecto
D * v = 
 [ 7 15]
Tich vo huong 2 vecto
u * v =  32
Giai he phuong trinh tuyen tinh
Nghiem cua he phuong trinh la:  [ 4. -1.]
Cong vecto
v1 + v2 =  [5 7 9]
Chuyen vi
Chuyen vi cua M la: 
 [[1 4]
 [2 5]
 [3 6]]


Day 8

In [15]:
import numpy as np
#cong ma tran kich thuoc khac 
print("Ex1: Cong ma tran kich thuoc khac:")
A = np.array([[3, 5], [7, 9], [2, 4]])
B = np.array([[1, 3], [6, 8]])
try:
    result = A + B
    print("A + B = \n", result)
except ValueError:
    print("Khong the cong ma tran kich thuoc khac nhau.")

#nhan ma tran voi vecto
print("Ex2: Nhan ma tran voi vecto:")   
D = np.array([[1, 4, 3], [5, 6, 7]])
v = np.array([2, 3, 4])
Dv = np.dot(D, v)
print("D * v = \n", Dv)

#tich vo huong 2 vecto
print("Ex3: Tich vo huong 2 vecto:")
u = np.array([4, 5, 6])
v = np.array([1, 2, 3])
dot_product = np.dot(u, v)
print("u * v = ", dot_product)

#cong ma tran va nhan ma tran
print("Ex4: Cong ma tran va nhan ma tran:")
A = np.array([[3, 2], [7, 1]])
B = np.array([[6, 8], [4, 5]])
A_plus_B = A + B
A_times_B = np.dot(A, B)
print("A + B =\n", A_plus_B)
print("A x B =\n", A_times_B)

#ma tran vuong vs dinh thuc
print("Ex5: Ma tran vuong va dinh thuc:")
M = np.array([[1, 3, 2], [4, 5, 6], [7, 8, 9]])
det_M = np.linalg.det(M)
print("Định thức của ma trận M =", det_M)

Ex1: Cong ma tran kich thuoc khac:
Khong the cong ma tran kich thuoc khac nhau.
Ex2: Nhan ma tran voi vecto:
D * v = 
 [26 56]
Ex3: Tich vo huong 2 vecto:
u * v =  32
Ex4: Cong ma tran va nhan ma tran:
A + B =
 [[ 9 10]
 [11  6]]
A x B =
 [[26 34]
 [46 61]]
Ex5: Ma tran vuong va dinh thuc:
Định thức của ma trận M = 9.000000000000002
